FROM node:20-alpine AS builder

WORKDIR /app
COPY frontend/package.json frontend/tsconfig.json frontend/next.config.ts frontend/postcss.config.js frontend/tailwind.config.js ./
RUN npm ci

COPY frontend/public ./public
COPY frontend/src ./src
ENV BUILD_STATIC=true
RUN npm run build

FROM nginx:alpine AS runner

COPY --from=builder /app/out /usr/share/nginx/html
COPY nginx/default.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
